apiVersion: v1
kind: Secret
metadata:
  name: tinyauth-secret
stringData:
  USERS: ENC[AES256_GCM,data:cFbuVVdExlM94gvWaC5h9Rhl3F+iGeGYMlxbYTwD+JAtBPONa49jkYV99DOJXW+1FnN1jhF+L22Z1tw0BwoTc45C,iv:YFN35+RoAh38JObzrTmSnKQ8gWMSC/Bh590keYAe9Qs=,tag:wl2y1bi+7+ffjvLk/WCHzw==,type:str]
  PROVIDERS_POCKETID_CLIENT_ID: ENC[AES256_GCM,data:ai86LeePzVHfk3M6MZU0GBR8sjjaQysDvKX2I16OP992IET4,iv:3jwkvhFPxFtbr8R9eVP+d2TIi8MEb3JQ2o92/00/l9g=,tag:xR0N/qGqbK8DEhmk4pH1wQ==,type:str]
  PROVIDERS_POCKETID_CLIENT_SECRET: ENC[AES256_GCM,data:jAUn9Gw2PBgQ72peNUb9z9hQiUgPiAZ+IPMWC7Latbk=,iv:sytxiYcaG9ckPyzS/MhW8y67/bo6Ts9LESRyk/W6zZ0=,tag:XkMe5Ic/AMIgBvWFZM6SrA==,type:str]
  PROVIDERS_POCKETID_AUTH_URL: ENC[AES256_GCM,data:hj8YUScJs3uzaBphSAY/+zavoZ6HlKryO3xl0utmcw==,iv:eEPWiUUDmLAjRx/a0YpGywIV9z5tbeP7YnUXVZrnBQs=,tag:aphtxPZU4FdEeuwTEK4wdQ==,type:str]
  PROVIDERS_POCKETID_TOKEN_URL: ENC[AES256_GCM,data:KN/vvCEE+/1GqlP9+0wAMQ/WcvmjpKpB1ZyQXxLwbUwAP3J9,iv:63oWB+4g10IirBXDDi7HmFajjF6wFGv18jI/ISjJvs0=,tag:7ncVPaguHlfLK3YX2xtmhA==,type:str]
  PROVIDERS_POCKETID_USER_INFO_URL: ENC[AES256_GCM,data:GRBvHjmBGlzEpe0Iav88hcurI8gl6+yQ0aKDv0jAJ3OmCxj4yAfy,iv:GfXeaetgGoQAmSm/bymwExtiD6BENbV5SOGZBJIGG+M=,tag:7/x3URzuv3SU2z/H6codTw==,type:str]
  PROVIDERS_POCKETID_REDIRECT_URL: ENC[AES256_GCM,data:Cm/QY6zzxra6jtWcY/ibHburHodrPQs67isSgoy97CczOx6FH89ptp0ydUT4kKxQOH7l8ELX,iv:IEf+ZXI4608/9YYpaC8XBH4ZfCiC8g6fUs0WmKIRKU4=,tag:lndHFMpHe+d7BUWlxbQKmQ==,type:str]
  PROVIDERS_POCKETID_SCOPES: ENC[AES256_GCM,data:mQge4ZJcoDDMz1Kg2oZKDWXiHQXTla+caLFc,iv:MZM8XTpU6vwsdDvH36Ira0MZogqUkjQqFBOFkBeV5kk=,tag:zNgL38mG8PdSTMmm2VTGyw==,type:str]
  PROVIDERS_POCKETID_NAME: ENC[AES256_GCM,data:nf+w+/54I5BQ,iv:+WeVUaAxoEFARsXpfDHXsnby6jqsI8UUl0Lb5a5Xqmo=,tag:KMQtBZuRFdfZo15b/wJBEA==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMHo0YkRDTVByWllxalE5
        Tk5NSkR1ci9NdW1GK0pOK2RpMzYxbTlrU2pJCmlVWDUxZFNEY3lqclJMR0NvZFhD
        ckNEaitRdGk3M1FsOCtiWXBLQVJ0VXMKLS0tIDhJUXV3ZlN0Vm01UnBQUGx2cEJx
        VnV3S3ZBdXQ5eWtlMENMTWpLb00rZ0kKAx9sX29QPpAHj4Gt3t2UKApaJTzKykAd
        uHBiE7mXKcyIl3CZOSU+spWWsSQowUxvhQMh/39YUKVlLh7yMBdO6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T21:06:30Z"
  mac: ENC[AES256_GCM,data:kzTYbKQp6RdCUFCwwFWE0uRuqBF3UL+1VicwU/5JbvuD+OW+i02ts5RV9dBvZMlRAPN+taf1As5nFppcJ0ENtbPlXycyTeN6biCNSMB5CHG+THCcYysNxp72OQiyWig2xo/xndvPwMsVbrupQSuHwX1xA5jhRzXClUmYImZuQ7M=,iv:yiCcBRqFVA7pzHfGpjaiJF9SyiD4GvoCBGBlXm0qmlg=,tag:uoAX5soTX/rZVwda/qN4+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
