---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: postgres-backup
  namespace: rook-ceph
spec:
  store: ceph-objectstore
  displayName: "PostgreSQL Backup User"
  capabilities:
    user: "*"
    bucket: "*"
