---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./oci-repository.yaml
  - ./helm-release.yaml
  - ./ceph-objectstore-user-volsync.yaml
  - ./objectbucketclaim-volsync.yaml
