---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: postgres-backups
  namespace: rook-ceph
spec:
  bucketName: postgres-backups
  storageClassName: ceph-bucket
  additionalConfig:
    # Max size for the bucket (optional)
    maxObjects: "1000000"
    maxSize: "500G"
