---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: volsync-backups
  namespace: rook-ceph
spec:
  bucketName: volsync-backups
  storageClassName: ceph-bucket
  additionalConfig:
    # Max size for the bucket (optional)
    maxObjects: "1000000"
    maxSize: "1000G"
