---
apiVersion: cilium.io/v2
kind: CiliumClusterwideEnvoyConfig
metadata:
  name: memos-http1-override
spec:
  resources:
    - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
      name: cloud:memos:5230
      type: EDS
      eds_cluster_config:
        service_name: cloud/memos:5230
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http_protocol_options: {}
