---
apiVersion: v1
kind: Service
metadata:
  name: memos-http1
  namespace: cloud
  annotations:
    service.cilium.io/lb-l7-protocol: "http"
spec:
  selector:
    app.kubernetes.io/controller: memos
    app.kubernetes.io/instance: memos
    app.kubernetes.io/name: memos
  ports:
    - name: http
      port: 5230
      protocol: TCP
      targetPort: 5230
      appProtocol: http/1.1
  type: ClusterIP
