---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immichframe-config
data:
  # ImmichFrame configuration
  # See: https://github.com/immichframe/ImmichFrame/blob/main/docker/example.env
  Interval: "10"
  TransitionDuration: "2"
  ImageZoom: "true"
  ImagePan: "false"
  Layout: "splitview"
  DownloadImages: "false"
  ShowMemories: "false"
  ShowFavorites: "false"
  ShowArchived: "false"
  RenewImagesDuration: "30"
  Rating: "5"
  RefreshAlbumPeopleInterval: "12"
  ShowClock: "true"
  ClockFormat: "hh:mm"
  ClockDateFormat: "eee, MMM d"
  ShowProgressBar: "true"
  ShowPhotoDate: "true"
  PhotoDateFormat: "yyyy-MM-dd"
  ShowImageDesc: "true"
  ShowPeopleDesc: "true"
  ShowAlbumName: "true"
  ShowImageLocation: "true"
  ImageLocationFormat: "City,State,Country"
  PrimaryColor: "#F5DEB3"
  SecondaryColor: "#000000"
  Style: "none"
  BaseFontSize: "17px"
  ShowWeatherDescription: "true"
  WeatherIconUrl: "https://openweathermap.org/img/wn/{IconId}.png"
  UnitSystem: "imperial"
  Language: "en"
