---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immichframe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: immichframe-secret
    creationPolicy: Owner
  data:
    - secretKey: IMMICH_API_KEY
      remoteRef:
        key: immich/api_key
    - secretKey: REFRESH_INTERVAL
      remoteRef:
        key: immichframe/refresh_interval
    - secretKey: PHOTO_PRELOAD
      remoteRef:
        key: immichframe/photo_preload
    - secretKey: KIOSK_MODE
      remoteRef:
        key: immichframe/kiosk_mode
