---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immichframe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: immichframe-secret
    creationPolicy: Owner
  data:
    - secretKey: ApiKey
      remoteRef:
        key: immich/api_key
