---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immichframe
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      immichframe:
        replicas: 1
        strategy: RollingUpdate
        pod:
          enableServiceLinks: false

        containers:
          main:
            image:
              repository: ghcr.io/immichframe/immichframe
              tag: v1.0.30.0
            envFrom:
              - configMapRef:
                  name: immichframe-config
              - secretRef:
                  name: immichframe-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi

    persistence:
      settings:
        type: configMap
        name: immichframe-settings
        globalMounts:
          - path: /app/data/Settings.yaml
            subPath: Settings.yaml
            readOnly: true

    service:
      immichframe:
        controller: immichframe
        ports:
          http:
            port: &port 8080

    route:
      immichframe:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Immich Photo Frame
          gethomepage.dev/group: Apps
          gethomepage.dev/icon: sh-immich.svg
          gethomepage.dev/name: Immich Frame
        hostnames: ["frame.tosih.org"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: immichframe
                port: *port
