---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: immichframe
      app.kubernetes.io/instance: immichframe
      app.kubernetes.io/part-of: immichframe
resources:
  - ./configmap.yaml
  - ./external-secret.yaml
  - ./helm-release.yaml
