apiVersion: v1
kind: Secret
metadata:
  name: immichframe-secret
type: Opaque
stringData:
  IMMICH_API_KEY: ENC[AES256_GCM,data:Wm7Q7Qg0pDHD,iv:EuuptGVtKiEQNIgU+CxGAPyLQZJzuOnCPZ/R99CBp3Y=,tag:xMVF7mNt1mFfrUIQw8irwA==,type:str]
  REFRESH_INTERVAL: ENC[AES256_GCM,data:EEs=,iv:l/+2vdoMeDMkVwuh7okEpG1EPxNpLmJCuQxi+LsuobE=,tag:jGzZSJUOQITU/6XCUay/UQ==,type:str]
  PHOTO_PRELOAD: ENC[AES256_GCM,data:5Q==,iv:kOZ2I+xSZvgQCBqYfZ8XuZOS83AsLouFFv4NVofAUVI=,tag:cKf+c5Cy0O78zXF1OnPe7g==,type:str]
  KIOSK_MODE: ENC[AES256_GCM,data:z9728Q==,iv:oADNLzx82Ian0jpnMV7ExF9mShcORMpwe04kqBSIAQs=,tag:WtWwmnjkSFQbab5moX9Nvw==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZklVQzZScDBMcVNLT0sz
        eEJGUGtabVE5YW85aGk1UmpQWTQydTB1b0Z3ClF4SHFQTXA1TXhCRzBwOFRNcVBX
        L3poM1Yrbms2ZytrRmdoUkVQR2ZXR2MKLS0tIHg0RVAzOVFKV3NZbm1PZS92OEwr
        Q041U1FaTkU0ZWpvbzgyYU12d1VyUkkKHPmonPz3yGua3lVvt34B1oSBWCRYquvF
        ipxMaDi0I7M3t28PGJDaWn0p2imUtbgRh31FAAv1ekkngV3ye6Apjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T22:43:40Z"
  mac: ENC[AES256_GCM,data:zX2swD+S1soR7GmIkZ8HtsunKdbDOg56w8IM/9Q3yimp/QrcmhaetUQtL6laT/GaZVbXPjiPa8v4rfZuHcjZ9TVI0qA5WocvwGmwJ4yRdPapem4xoGisOR+rf86XZa4p9Wds8Aamkw5F8Pu13xErOS1sFwipEsAFjK5WJ5pR5cs=,iv:1vLiNNskGaGs8hM7A22VSLvO0ug5sJzu7SrJNF9S6oE=,tag:NglxjpuSerCHbP95dG1PHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
