---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: linkding
  namespace: cloud
spec:
  database: linkding
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: linkding-user
  namespace: cloud
spec:
  role: linkding
  database: linkding
  secretName: database-linkding-user
  privileges: OWNER
