apiVersion: v1
kind: Secret
metadata:
  name: linkding-oidc-secret
  namespace: cloud
type: Opaque
stringData:
  OIDC_RP_CLIENT_ID: ENC[AES256_GCM,data:NWm0cvd1xBTN4GiMhaKTbJ0AnW9E281QItBlIWeG1p56X2Y8,iv:igdv2+Hlf7T05aegXO5HRpMNTNfIq6sGI6yq0NQGG1o=,tag:u8neTcAc/xxDzeJ8BBfWhA==,type:str]
  OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:cWJLAmJA1O59RQUEinnU0KG1woRMF35u8QAsKT1bUnQ=,iv:WxqyTSs/s0Yp5tLzMNnful/y/kwHQPcWxXRTLxyJg88=,tag:fq5JGlzNy1pjmRT4k4v9Jw==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUVR4WG9RZ0EwaE1URUlu
        N0hMVXRFb0FVcUM2M1BJb0hweDFKRk1BYkQ0CmsxY05iZHZMYmVEakRCN1NHd3JD
        LytOenBPTmR0amRPeENJNTlONXhrZVEKLS0tIEtObHNoNnJ1Y1JwYnkyRWU4eWV1
        ck4yOEJnbWY5c3U5K0hYYnNDdnpnVFkKHYszGdZlCOObUz3a6utuWfGwyBrANNwb
        kMI8wf830bBSm2D1jQj3hd7HrBCCUI8qYtL+p+jpqIT4BGBLi0AUzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T07:58:56Z"
  mac: ENC[AES256_GCM,data:11iV66qOghChbt047oFt5DPUryme6AoIka9LdLvyWuKqt9GnE2WJseI4+rcQgiXWpzLa6fnqqDOsK3oVzyfAUCzbIkVk1ybxY5U2M/sq/gxdDK0oFXQWbC64TRleBKwypwdDpFQ+WU8YREJ1Cj6Y8K3J+yNuap6INMKKNrdCJzY=,iv:mkttJztvGcMYRILGjukMZKUxPYjrh0DKOxGJVkrJSyk=,tag:t9wYhxQpK5zHWaaNO2Ktdg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
