---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: immich-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: IMMICH_OIDC_CLIENT_ID
      remoteRef:
        key: immich/oidc_client_id
    - secretKey: IMMICH_OIDC_CLIENT_SECRET
      remoteRef:
        key: immich/oidc_client_secret
