---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./media-nfs-pv.yaml
  - ./downloads-pvc.yaml
  - ./audiobookshelf/ks.yaml
  - ./beets/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./nzbget/ks.yaml
  - ./recyclarr/ks.yaml
