---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: jellyseerr
  namespace: media
spec:
  database: jellyseerr
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: jellyseerr-user
  namespace: media
spec:
  role: jellyseerr
  database: jellyseerr
  secretName: database-jellyseerr-user
  privileges: OWNER
