---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: home
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Smart home and automations
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: sh-home-assistant.svg
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/app: home-assistant
spec:
  hostnames:
    - home.tosih.org
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: oauth2-proxy-home-assistant
          port: 4180
