---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./database.yaml
  - ./helm-release.yaml
  - ./httproute.yaml
  - ./oci-repository.yaml
  - ./oidc-secret.yaml
  - ./oauth2-proxy.yaml
