---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: home-assistant-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: home-assistant/oidc_client_id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: home-assistant/oidc_client_secret
