---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud
components:
  - ../../components/common
resources:
  - ./immich/ks.yaml
  - ./immichframe/ks.yaml
  - ./nextcloud/ks.yaml
  - ./memos/ks.yaml
  - ./romm/ks.yaml
  - ./syncthing/ks.yaml
