apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
  namespace: network
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:TqxlGS65i4Ernp5zdL/CJQKeHYbK9RILNiGwaI+JZ4pkhPr0hMVATg==,iv:7RFIhatuiP5gBbsmrB5GfnaDZwVdJ/o0fKVZoiOSV/A=,tag:b263FmpHLlOuND7d0csSwQ==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NE1sbnYvVnloOWI4d1hR
        Q0poaVRWSHJ2a1EvRjZrMitaaFVTaGYvdENBCkRvaFcwbDVqbkoxWmlIKzBRQ3ZZ
        dXdUZGRoeVZ3aER3L0tKYjBKeHdhNFUKLS0tIHVpb1EwL01YOUZrS2ZjcWdjWXNm
        RUJ1RjI4THZoY05xWXBhVGd0U1pyQkEK21jo1tUKcKIqOEVuN2E8eGc+mJwrfOhM
        2ogSX9f9hOWSVu7gsHFOHeM46kmZkxU5a6E0U9GB5lkHuGasPh4Oig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T07:52:28Z"
  mac: ENC[AES256_GCM,data:DTEhc2qENc9cvWAuJIe4uEmmeYLN0RiH/eL/G9LSSEc8C5SDe5JcjPI0JUnuR8h6XmCUYnT6Mx1U46N/AnaJrPl6XVKNDJplNSoPl7/So3XO3bX/TTDSzykGHHBN/Zx8ID3qEg3DSam4hsjFUrIbx93BRkhT4o0dWmTJiACgf0s=,iv:V6yjNbS/h2FI/l8xMlGxdtpdTnMUxuOOn95mMlumYqg=,tag:ps+2qwYNv8wVgbo+lNUrxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
