apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin-secret
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:44iLUG3gkrcX,iv:WQjSCuEaovF5zGS/pwTjiqGtRTCOIs00E/jRDHcetJE=,tag:UY1tjQJi9ExvcXYc5rYV3g==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a05nRXQvdEFzZlJJZmg5
        YktHZTNva3h6M0FFSHFteGhoQnh3WDYybXlBCmR1bTlCdk9RYVRLN1h2ZG9TVkt6
        dWZWWEtXRm1nWm8zcmxMRHRVcEgxdnMKLS0tIFVYckVtU1R6RG1PN0hOYWlnZmps
        UmwrZnhGWWQzRXdubHhLTWMyVXdVL2sKihnHYEhIo5AjKgIjYJQ9NMVzGG929s1w
        XxQzTiBcH2l9K8JXl1zskslK+7qwOUOJshG8SZaK3oiaHuD/k764nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T06:30:31Z"
  mac: ENC[AES256_GCM,data:0rUgKClIIS7kPi4+X5TcQh1QkHJHpVlNlo68Qu/PgeRitJSNjWbXnkI5bd9rArUqvW+UqLb1QnPOpAc82dUzkYaPrY/38YOIGHDVb6vc92oc9nHHaNmAiHjBATU2d6BHOCzo7aNar+k183m8VB0bva9aGIP0kbYCiT9drrtY+FI=,iv:DP1m2WQglazjAtC6qsZym75Qb5fdEz6GSBW2PugscNI=,tag:9AoAeDO+zwL5bYTiEhsdhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
