---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: authelia-db
spec:
  database: authelia
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: authelia-user
spec:
  role: authelia
  database: authelia-db
  secretName: database
  privileges: OWNER
