---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authelia-secret-reader
  namespace: security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authelia-secret-reader
  namespace: security
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authelia-secret-reader
  namespace: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authelia-secret-reader
subjects:
  - kind: ServiceAccount
    name: authelia-secret-reader
    namespace: security
