apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
type: Opaque
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:c1eOAm6t5bYWn6Rrq9IP3kkPJ6u40Ly4rqialyUIXU8=,iv:nwpT2S8t6wuE9Kv8DcIcdBEF6YXp1E92UGIXEsDKFM8=,tag:dBSEtLc+CoHcdmlH0bFa2A==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:wC50tMPBvnRNAKGIIS8T9BL9bNzxooslUf9PukNsyf4=,iv:Pc0SQI/ouhromA1Qw3uMNXY7tBKz0RodE/kXjIl+UBM=,tag:JWcYWeAFWwLwLWhxMV4LoQ==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aERRZk1UelRGRkltcC94
        SEllakFUSGZRK0V1dW1rdzUvM3UvNURQeGlnCjBFMDNvL3haQkdDbURZUTVnNkxE
        eTBWR1h4Y1FlQWZBQXhseS9TeVI3Y00KLS0tIFl5N2tZcFBFUlY4alp5R291N1Rv
        c1dQa3U2NTJMaThBR0NFUzE2eUtVQncKD/BRf/uEj2TURF9kbPzkx42XIokaOfcE
        po73++NKjFYxysqnPCwXdk6Es9stDYzzwalSrnH1nCa+m2PJhpPySw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T05:23:54Z"
  mac: ENC[AES256_GCM,data:dq1+dsRJfHZkJcJpinGHVMiLIuD8iuCBk7//akfeLh/W1KHhj/vHOLY9COw62nvAD084MDDw62ngVww56VNCSS7ylHJtvq/HPJy+7icVjq2UCnNVjbTm+w4wf6zcbDzkQWJ8mjcnzziYhkxjtFbGfYo8gGrE556EmcmU45xIlEE=,iv:eT7nR+RYbVY6dA9kf1B1fIjYb44189/ceLJ9+i4X/L4=,tag:HD9rPTQjQW/8LEnzRNU6FA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
