apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
type: Opaque
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:FKp2XrdqnGMhuXFPUq5U3ME1+781aqwS2EyqgdLP9V4=,iv:7LnHo+NYyigat34PB6yIvvkdQcBnXjKTFuXox2pQuAo=,tag:Cpcvt3QcmH4bSfZUB1i8/Q==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:GCykQILIzcX4TTqjqzSZ2OupHcvK5ZJY1ljLkmrXc84=,iv:x6w8iViuM4LpPW+BdtdftGHErRnOyByRvxbhvlGfxkk=,tag:VSbNc/EXBu5ChT6drstiIA==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aERRZk1UelRGRkltcC94
        SEllakFUSGZRK0V1dW1rdzUvM3UvNURQeGlnCjBFMDNvL3haQkdDbURZUTVnNkxE
        eTBWR1h4Y1FlQWZBQXhseS9TeVI3Y00KLS0tIFl5N2tZcFBFUlY4alp5R291N1Rv
        c1dQa3U2NTJMaThBR0NFUzE2eUtVQncKD/BRf/uEj2TURF9kbPzkx42XIokaOfcE
        po73++NKjFYxysqnPCwXdk6Es9stDYzzwalSrnH1nCa+m2PJhpPySw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T17:44:42Z"
  mac: ENC[AES256_GCM,data:zjkOCNY680RGQFP93tVN1WXZNLYHYE6AWuBA5tij2bazzP50kkrD0oGT7nHJUkCERcAWGM2OVU+yw+S97eiGeq9tuZNuYhDk1ZRxSmvrMDYETQtKfbHv7pNC2a/N0qMUI3A6ZA51az3omUmNFq+NMaBYWD+c4bVD32YxYvyIvDE=,iv:mcUoOk5SqefHLnIig0h9Pue6HMlif0e8IvK8I0ECWPE=,tag:nW9IY3xKrbL7ALY4ct1sKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
