---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  # - ./eufy-security-ws/ks.yaml
  # - ./home-assistant/ks.yaml  # Disabled for reinstall
  - ./homebridge/ks.yaml
  # - ./scrypted/ks.yaml  # Disabled
components:
  - ../../components/common
