---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
components:
  - ../../components/common
resources:
  - ./external-secrets/ks.yaml
  - ./onepassword/ks.yaml
  - ./pocket-id/ks.yaml
  - ./tinyauth/ks.yaml
