apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-token: ENC[AES256_GCM,data:ydrdfT7h6gNKUfr58kNzEwhybt3DjSbCcoBMEYB3JhevmT+gOFZzGw==,iv:il0AhDQQXSfX8psizjSiyR/7VTZs4hLbBJVDyNEmVyg=,tag:KjdHKHnQaR3n85+vrYT4kw==,type:str]
sops:
  age:
    - recipient: age1ns2zygls77xarjsxvhgllgdah7p9sl2220dlj9jtwmeydmta6qpsnzcx2h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIekF4NDE2SUxHYmg3WmNz
        bUVMemh4K1QzakVsaDMzTEVoZzNvUno0cVV3CkxKYnovc1JKRDRnRUw2N1FKcmZD
        MzcvcVRWYUs4RC9qVUtoUjMyZVZLdlkKLS0tIGJKYXg5RU82aU9qdGJyLzhMUVhC
        cnVCVTFKYSsvMkorWUxPRHlOL05zK1EKbRz3jyJXi6wqIF2qPprg3j6hj4YdzlOR
        3SV3upw4YNbW6rqYWdzHaLevyGTEiSC8XUz1rKLzZi4aKPpnS7yGSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T07:47:41Z"
  mac: ENC[AES256_GCM,data:e8nsRp+pWzmhhOWVm3DnXRCpPgvlCK4jIMXAz5WJduvyxyPlsyBMLD1PVgylpI6W6I80ho4TQDJG68zr55Q5j3+7hLdrc+XsP5NZTha5fclFsBDGpTQ88Pb9PJMqmTh8sZdxXquZGlXVxNsU3culPi6eKhEb4Guyxav9xxcUNYE=,iv:B+nAlCo2aI/Xn81O90mZS1paewuwk/e47wOk5OqfyZc=,tag:gMT6AFunikVGLp737x64KA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
