---
apiVersion: v1
kind: ConfigMap
metadata:
  name: romm-configmap
data:
  # OIDC Configuration
  OIDC_ENABLED: "true"
  OIDC_PROVIDER: "pocketid"
  OIDC_REDIRECT_URI: "https://romm.tosih.org/api/oauth/openid"
  OIDC_SERVER_APPLICATION_URL: "https://pid.tosih.org"
