---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: romm-secret
    creationPolicy: Owner
  data:
    - secretKey: STEAMGRIDDB_API_KEY
      remoteRef:
        key: romm/steamgriddb_api_key
    - secretKey: ROMM_AUTH_SECRET_KEY
      remoteRef:
        key: romm/auth_secret_key
    - secretKey: SCREENSCRAPER_USER
      remoteRef:
        key: romm/screenscraper_user
    - secretKey: SCREENSCRAPER_PASSWORD
      remoteRef:
        key: romm/screenscraper_password
