---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: zfs-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: zfs-nfs
